### ISSUE TITLE
Umstellen auf https://coalbase.archi-lab.io/

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/coalbase-documentation#3]
* Aus Gründen von Einheitlichkeit und Kosten sollten wir zukünftig alle Entwicklungsprojekt als https://<xxx>.archi-lab.io fahren.

**Comment by MarcSchmidt** [comment]
Die Domänen sind alle eingerichtet. Die neuen Bezeichnungen können jetzt eingepflegt werden um später die alte Domäne coalbase.io abzuschalten
